### ISSUE TITLE
Modularity on Swarm example

### ISSUE THREAD

**Issue by iromli** [GluuFederation/enterprise-edition#18]
Current Swarm example requires users to modify manifests to choose which services deployed to swarm cluster. The ease the operation, the examples should adhere to [Compose](https://github.com/GluuFederation/community-edition-containers/tree/4.0/examples/single-host) and/or [Kubernetes](https://github.com/GluuFederation/enterprise-edition/tree/4.0/examples/kubernetes) examples that are modular.

**Comment by moabu** [comment]
Support for Swarm has been deprecated.
