### ISSUE TITLE
Proper Helm Chart Needed

### ISSUE THREAD

**Issue by kferrone** [GluuFederation/enterprise-edition#2]
So it seems to be there is no actual Helm chart for Gluu yet. This project only shows off some example manifests which are not dynamic and only work for minikube. 

There is [this project](https://github.com/GluuFederation/k8s-gluu-server) as well. However there really isn't anything suggesting it uses Helm. I also posted a [similar issue](https://github.com/GluuFederation/k8s-gluu-server/issues/4) on that project as well. 

Over the last few weeks, I have built a proper chart for Gluu. The company I work for is Akirix, and they allowed me to share my work with ya'll. Hoping our Helm chart could help with Gluu getting out an official Gluu Helm Chart. Please check this project out and fork if you need. 

[Akirix/Gluu](https://github.com/Akirix/gluu)

I basically used the [Gluu minikube example](https://github.com/GluuFederation/gluu-docker/tree/3.1.4/examples/kubernetes/minikube) and the [stable helm charts](https://github.com/helm/charts/tree/master/stable) as the pattern to follow. 

Our project is not done nor documented enough and therefore may not be the easiest Chart to use. We are definitely hoping ya'll can finish what we started using your master knowledge of Gluu. Then the community would be complete with an up to date Helm chart. 

[Akirix/Gluu](https://github.com/Akirix/gluu)

**Comment by moabu** [comment]
Helm Gluu chart has been released ![CDNJS](https://img.shields.io/badge/beta-red.svg?style=for-the-badge).
