### ISSUE TITLE
Confusing oxTrust API prompt in create.sh

### ISSUE THREAD

**Issue by mzico** [GluuFederation/enterprise-edition#25]
![Capture](https://user-images.githubusercontent.com/7156097/71985261-e2309180-31ef-11ea-90de-ed51fc0b2055.PNG)

There are: 

- `Enable oxTrust Api` 
- `Enable oxTrust Test Mode`. 

I am not sure what 'oxTrust Test Mode' is, talked to Gasmyr and he suggested it's wrong. Please talk to Gasmyr and remove which is not necessary.

**Comment by moabu** [comment]
Hey this is a feature not something that is wrong. It allows UMA and Testmode to be enabled upon installation and use the API directly without going to the GUI.

 https://github.com/GluuFederation/enterprise-edition/issues/15
