### ISSUE TITLE
Show the 'list' of items which user just entered during installation

### ISSUE THREAD

**Issue by mzico** [GluuFederation/enterprise-edition#26]
![Capture1](https://user-images.githubusercontent.com/7156097/71985399-2754c380-31f0-11ea-8a88-d5c54e90bb6a.PNG)

`Continue with the above settings` 

May be we can show the 'list' of settings ( the way CE showing ) after user is done with password? And after that... prompt with `Continue with the above settings` message.

**Comment by moabu** [comment]
`create.sh` will be depreciated and replaced with python3 #19  which will output the settings. I will keep this open until we finish #19
