### ISSUE TITLE
Add ability to casa image to load `casa.json` automatically into the backend

### ISSUE THREAD

**Issue by moabu** [GluuFederation/enterprise-edition#31]
Currently to use casa the user must move `/etc/gluu/conf/casa.json` to the backend manually. This step has to be automated to load at:

```
dn: ou=casa,ou=configuration,o=gluu
objectClass: top
objectClass: oxApplicationConfiguration
ou: casa
oxConfApplication: < ... contents of casa.json ... >
```

**Comment by iromli** [comment]
See https://github.com/GluuFederation/docker-casa/issues/1

**Comment by moabu** [comment]
GluuFederation/docker-casa#1 adds this enhancement
