### ISSUE TITLE
Move ingress chart out from the main chart

### ISSUE THREAD

**Issue by moabu** [GluuFederation/enterprise-edition#34]
With the nginx-ingress required to be installed before the rest of the chart and it operating on a different namespace  we should just switch to two `helm installs` instead of having the user minipulate the main `values.yaml` `helm install` then manipulate again and `helm upgrade`.

https://github.com/GluuFederation/enterprise-edition/tree/4.0/helm/charts/nginx-ingress

**Comment by mirr254** [comment]
This has been handled by this PR #30 
Also, since we are not the maintainers of `nginx-ingress` chart, I decided that users should install it from the official chart repository. But I have however included the instructions of values to change in the documentation.
