### ISSUE TITLE
Don't ask for Shibb storage if Shibboleth installation is "No" 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/enterprise-edition#36]
Though I selected `N` for Shibboleth but setup script ( create.sh ) asked for "Shared Shibboleth Volume" input. 

It will be good if this "Shared Shibboleth Volume" appear only if deployer select 'Y' for Shibboleth. 

![Capture](https://user-images.githubusercontent.com/7156097/73605474-5a2a7700-4564-11ea-8c82-fee25ac45f2e.PNG)

**Comment by moabu** [comment]
It is addressed in the new script #19. Will close this issue upon the pre-release of python3 script
