### ISSUE TITLE
Add Gluu Gateway and Gateway UI images

### ISSUE THREAD

**Issue by moabu** [GluuFederation/enterprise-edition#5]
Create image and manifests to use Gluu Gatway.
https://gluu.org/docs/gg/

**Comment by iromli** [comment]
Image development progress can be tracked in https://github.com/GluuFederation/docker-gg and https://github.com/GluuFederation/docker-gg-ui.

**Comment by mirr254** [comment]
Gluu Gateway 4.1 is ready and under review. Next one is the Gateway UI

**Comment by mirr254** [comment]
Gateway image is done and under review.

**Comment by moabu** [comment]
Images have been created under repo https://github.com/GluuFederation/docker-gg, and https://github.com/GluuFederation/docker-gg-ui
