### ISSUE TITLE
Add License file 

### ISSUE THREAD

**Issue by moabu** [GluuFederation/enterprise-edition#7]
Add License enforcement in our EE edition. This needs to be in our GUI , ask for a license file and have a back end server approve this license.

**Comment by mogluu** [comment]
Remove all EE license from docker images. Link all yawls and scripts to support license and prompt user to accept it. 

https://www.gluu.org/support-license/

**Comment by moabu** [comment]
License headers are added to all the associated files. `./pygluu-kubernets.pyz` also prompts the user for accepting the license file.
