### ISSUE TITLE
IDP configuration files are not properly pushed to oxshibboleth pod(s) in k8s cluster setup

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/enterprise-edition#88]
## Environment

- AWS k8s cluster setup built according to the Gluu official recipe [here](https://gluu.org/docs/ce/installation-guide/install-kubernetes/)
- `pygluu-kubernetes-linux.pyz` version 1.0.2
-  Gluu Server components are of version 4.0.1
- 3 `oxshibboleth` pods initially, but is reproducable for a single pod a well
- 2 `oxtrust` pods
- ping me for more details, if needed, I can share full `settings.json` file of my deployment

## Description

When a new SAML TR is added using oxTrust, the SP is recognized by IDP (so metadata is updated and loaded), but other settings (released attributes, encryption/signing settings etc) don't seem to apply in case of a single IDP pod, and only apply sometimes in case of 2+ IDP pods.

As explained by @moabu , SAML TR-related changes in oxTrust are pushed to `/opt/shibboleth-idp/` first, and then get moved to `/opt/shared-shibboleth-idp/` - which is the shared volume between oxtrust and oxshibboleth.

Then oxshibboleth pods pick up on change in this volume at `/opt/shared-shibboleth-idp` and move the changes from `/opt/shared-shibboleth-idp/` to `/opt/shibboleth-idp/`

Apparently, somewhere along this flow the process is broken.

## Preconditions

K8s cluster is created according to mentioned layout

## Steps to reproduce

1. Make sure there are 3 running pods for `oxshibboleth` deployment:
  - to see list of pods: `# kubectl get pods -w`
  - to scale `oxshibboleth` deployment to 3 pods (you may need to wait until all pods will start): `# kubectl scale statefulset oxshibboleth --replicas=3`

2. Create a SAML TR for samltest.id's SP; release a few attributes and configure SAML2SSO profile in Relying Party Configuration

3. Verify that changes you've done a correctly pushed to both oxTrust's IDP directories:
  - `# kubectl exec -ti oxtrust-0 -- cat /opt/shared-shibboleth-idp/conf/attribute-filter.xml`
  - `# kubectl exec -ti oxtrust-0 -- cat /opt/shibboleth-idp/conf/attribute-filter.xml`

4. Check state of similar IDP conf dirs in all running `oxshibboleth` pods:
  - to see list of pods: `# kubectl get pods -w`
  - `# kubectl exec -ti oxshibboleth-0 -- cat /opt/shibboleth-idp/conf/attribute-filter.xml`
  - `# kubectl exec -ti oxshibboleth-0 -- cat /opt/shared-shibboleth-idp/conf/attribute-filter.xml`

5. Scale down `oxshibboleth` to one pod and repeat checks from step 4)

## Results

- At step 4, when tested with 3 `oxshibboleth` pods, whatever change is done for saml TR in web UI, it’s only oxshibboleth-1 pod that mirrors it; oxshibboleth-0 had an example set of files (default config files which come with IDP); oxshibboleth-2 pod always kept its “empty” configuration (for the lack of better word, it was neither the current config, nor the example ones)

- it also was same for all main config files, not just attribute-filter.xml used in command examples

- if deployment is reduced to just one pod, there is only oxshibboleth-0 pod and it contained the same example config files oxshibboleth-0 pod had in 3 pods deployment, and wasn’t changed at all, despite shared files in oxtrust pod were changed correctly

- In `oxshibboleth` pods, ` /opt/shared-shibboleth-idp/` directory is empty

**Comment by aliaksander-samuseu** [comment]
@moabu 
I've also noted just now that in case when `oxtrust` deployment has more than one pods, when SAML TR is created or updated, only one of the pods get files under `/opt/shared-shibboleth-idp/conf/` and `/opt/shibboleth-idp/conf/` dirs updated.

**Comment by moabu** [comment]
resolved by https://github.com/GluuFederation/enterprise-edition/commit/3cb5d24496f6e6478357a434a83246598e671a0b
