### ISSUE TITLE
Port name for Istio should be prepended with protocol.

### ISSUE THREAD

**Issue by zaphod72** [GluuFederation/enterprise-edition#90]
https://github.com/GluuFederation/enterprise-edition/blob/ddb61345000101faa21bca2dc26e4850a2ef7a89/pygluu/kubernetes/templates/oxauth/base/services.yaml#L10

Should be
```
  ports:
  - name: http-oxauth
```

**Comment by moabu** [comment]
Yes. https://github.com/GluuFederation/enterprise-edition/blob/istio-integration/pygluu/kubernetes/templates/helm/gluu/charts/oxauth/templates/service.yml#L13. And this is just initial work we have up and is not in function yet. You can track the issue [here](https://github.com/GluuFederation/enterprise-edition/issues/3)
